apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deploy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
    labels:
      app: java-app
    spec:
      containers:
      - name: java-app
        image: nikhilkumar11/poc-devops:poclatest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
  
